# Generated by Django 2.0 on 2019-01-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, unique=True)),
                ('pwd', models.CharField(max_length=32)),
            ],
        ),
    ]
