# Generated by Django 2.0 on 2018-12-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20181212_0718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
