# Generated by Django 2.0 on 2018-12-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
