# Generated by Django 2.0 on 2018-12-13 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app01.Publisher'),
        ),
    ]
