# Generated by Django 2.0 on 2018-12-13 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_book_publisher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher_id',
            new_name='publisher',
        ),
    ]
