# Generated by Django 2.0 on 2018-12-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20181213_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='addr',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
