# Generated by Django 2.0 on 2018-12-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20181225_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField(default=18)),
                ('birthday', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
