# Generated by Django 2.0 on 2018-12-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=5),
        ),
    ]
