# Generated by Django 2.0 on 2018-12-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='kucun',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='book',
            name='maichu',
            field=models.IntegerField(default=9),
        ),
    ]
