# Generated by Django 2.0 on 2018-12-28 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_auto_20181228_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=32, verbose_name='爱好')),
                ('addr', models.CharField(max_length=128, verbose_name='地址')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.AuthorDetail'),
        ),
    ]
