# Generated by Django 2.0 on 2018-12-28 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_auto_20181228_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('book', models.ManyToManyField(to='app01.Book')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.AuthorDetail')),
            ],
        ),
    ]
