# Generated by Django 2.0 on 2019-01-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
