# Generated by Django 2.0 on 2019-01-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_auto_20190104_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
