# Generated by Django 2.0 on 2019-01-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_auto_20190104_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
